# In this notebook, we are going to cover some of the most fundamental concepts of tensos using TensorFlow
More specifically, we're going to cover:
* Introduction to tensor
* Getting information from tensors
* Manipulating tensors
* Tesnor & Numpy
* Using @tf.function (a way to speed up your regular Python functions)
* Using GPUs with Tensorflow(or TPUs)
* Exercises to try yourself!



## Introduction to   Tensors

In [1]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)


2.18.0


In [ ]:
# Creating tensors with tf.constant
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Check the number of dimensions of a tensor(ndim stands for number of dimensions)
scalar.ndim

0

In [ ]:
# Create a vector
vector = tf.constant([10, 10])
vector


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
# Check the dimensions of the vector
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
# Create a matrix(has more than 1 dimension)
matrix = tf.constant([[10, 7],
                      [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
# Cretae another matrix
another_matrix = tf.constant([[10., 7.],
                              [3., 2.],
                              [8., 9.]], dtype=tf.float16) # speficy the data type with dtype parameter
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
# What's the number dimensions of the another_matrix
another_matrix.ndim

2

In [ ]:
# Let's create a tensor
tensor = tf.constant([[[1, 2, 3,],
                       [4, 5, 6]],
                       [[7, 8, 9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor


<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

What we've created so far:

* Scalar: a single number
* Vector: a number with direction (e.g. wind speed and direction)
* Matrix: a 2-dimensional array of numbers
* Tensor: an n-dimensional array of numbers (where n can be any number, a 0 dimensional tensor is a scalar, a 1-dmensional tensor is vector, 2- dimensional tensor is called a matrix, 3-demsnional tensor is called a rank-3 tensor, 4-dimensional tensor is a rank-4 tensor.

### Creating tensors with `tf.Variable`

In [ ]:
# Create the same tensor with tf.Variable as above
changeabale_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeabale_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
 # Let;s try change one of the elements in our changeable tensor
changeabale_tensor[0] = 7
changeabale_tensor # -->error

TypeError: 'ResourceVariable' object does not support item assignment

In [ ]:
# How about if we try .assign
changeabale_tensor[0].assign(7)
changeabale_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
# Let's try change our unchangeable tensor
unchangeable_tensor[0].assign(7)
unchangeable_tensor

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

### Crreating random tensors
Random tensors are tensors of some abitrary size which contain random numbers

In [ ]:
# Create 2 random (but the same) tensors
random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1 = random_1.normal(shape=(3, 2 ))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2))

# Are they equal?
random_1, random_2, random_1 == random_2

### Shuffle the order of the elements

In [ ]:
 #Shuffle a tensor (valuable for when you want to shuffle your data, so the inherit order of the data does not affect learning )
not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [2, 5]])
# Shuffle our non_shuffled tensor
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

In [ ]:
# Shuffle our non_shuffled tensor
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [ ]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

🛠️**Exercise:** Read through Tensorflow documentation on random seed generation: https://www.tensorflow.org/api_docs/python/tf/random/set_seed and practise writing 5 random tensors and shuffle them

It looks like if we want our shuffled tensor to be in the same order, we have to use global level random seed as well as the operational level random seed:

> Rule 4: If  both the global and the operational seed are set: Both seeds are used in conjunction to determine the random seqeunce

In [ ]:
tf.random.normal([3, 2])  # generates 'A1'
# print(tf.random.uniform([1]))  # generates 'A2'

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.3274685, -0.8426258],
       [ 0.3194337, -1.4075519],
       [-2.3880599, -1.0392479]], dtype=float32)>

In [ ]:
tf.random.uniform([3, 4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0.68789124, 0.48447883, 0.9309944 , 0.252187  ],
       [0.73115396, 0.89256823, 0.94674826, 0.7493341 ],
       [0.34925628, 0.54718256, 0.26160395, 0.69734323]], dtype=float32)>

#### If neither the global seed nor the operational seed is set, we get different results for every call to the random operation and every re-run of the program

In [ ]:
print(tf.random.uniform([1])) # Generates 'A1'
print(tf.random.uniform([1])) # Generates 'A2'

tf.Tensor([0.7413678], shape=(1,), dtype=float32)
tf.Tensor([0.7402308], shape=(1,), dtype=float32)


#### Now close the program and runt it again


In [ ]:
print(tf.random.uniform([1])) # Generates 'A1'
print(tf.random.uniform([1])) # Generates 'A2'
# Getting different result every time I run the code, there is no reproducibility


tf.Tensor([0.803156], shape=(1,), dtype=float32)
tf.Tensor([0.95831835], shape=(1,), dtype=float32)


#### If the global seed is set, but the operational seed is not set, we get different results for every call to the random operation, but the same sequences for every re-run of the program

In [ ]:
tf.random.set_seed(1234)
print(tf.random.uniform([2]))  # generates 'A1'
print(tf.random.uniform([2]))  # generates 'A2'

tf.Tensor([0.5380393  0.36461866], shape=(2,), dtype=float32)
tf.Tensor([0.3253647 0.1387006], shape=(2,), dtype=float32)


##### ( now run program again)

In [ ]:
tf.random.set_seed(1234)
print(tf.random.uniform([2]))  # generates 'A1'
print(tf.random.uniform([2]))  # generates 'A2'

tf.Tensor([0.5380393  0.36461866], shape=(2,), dtype=float32)
tf.Tensor([0.3253647 0.1387006], shape=(2,), dtype=float32)


In [ ]:

print("This is the example number 1: \n {0}".format(tf.random.normal([1])))
print("This is the example number 2: \n {0}".format(tf.random.normal([1, 2])))
print("This is the example number 3: \n {0}".format(tf.random.normal([1, 3])))
print("This is the example number 4: \n {0}".format(tf.random.normal([2, 1])))
print("This is the example number 5: \n {0}".format(tf.random.normal([2, 2])))


This is the example number 1: 
 [0.95883226]
This is the example number 2: 
 [[-0.37767014 -0.2148674 ]]
This is the example number 3: 
 [[ 1.8121718 -2.7747965  0.7068178]]
This is the example number 4: 
 [[-0.3198804]
 [ 1.3575249]]
This is the example number 5: 
 [[ 0.803483   -0.36864722]
 [-0.76201993 -0.3464329 ]]


#### Let's create 5 random tensors and then shuffle them


In [ ]:
# Creating unshuffled tensors
tensor1 = tf.random.normal([1,2])
tensor2 = tf.random.normal([2,2 ])
tensor3 = tf.random.normal([3, 2])
tensor4 = tf.random.normal([3, 3])
tensor5 = tf.random.normal([3, 4])

print(" These are the list of tensors created: \n First: {}, \n Second: {}, \n Third: {}, \n Fourth: {}, \n fifth: {}".format(tensor1, tensor2, tensor3, tensor4, tensor5))

 These are the list of tensors created: 
 First: [[-1.3400401  -0.79816866]], 
 Second: [[-0.16868056  1.0764664 ]
 [ 0.4020387   0.8481271 ]], 
 Third: [[-1.9150431e-01  1.2460954e+00]
 [ 4.0446193e-04 -2.7550116e-01]
 [-1.0030401e+00 -7.2526878e-01]], 
 Fourth: [[-0.6111528  -0.25865728 -0.826007  ]
 [-1.1821938   0.15866472  0.43112957]
 [ 1.5888466  -1.0824435  -0.7191452 ]], 
 fifth: [[-1.5631174   1.2649965  -1.122423   -0.3348183 ]
 [-1.3077002   0.09411693 -0.8668549  -1.9196522 ]
 [ 0.66733    -1.1789492   0.981988    2.1274676 ]]


In [ ]:
# Let's shuffle the non-shuffled tensors

tf.random.shuffle(tensor1, seed=42)
tf.random.shuffle(tensor2, seed=24)
tf.random.shuffle(tensor3, seed=32)
tf.random.shuffle(tensor4, seed=45)
tf.random.shuffle(tensor5, seed=54)


<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 0.66733   , -1.1789492 ,  0.981988  ,  2.1274676 ],
       [-1.5631174 ,  1.2649965 , -1.122423  , -0.3348183 ],
       [-1.3077002 ,  0.09411693, -0.8668549 , -1.9196522 ]],
      dtype=float32)>

In [ ]:
# Let's shuffle the non-shuffled tensors

#  setting the global seed
tf.random.set_seed(42)
tf.random.shuffle(tensor1, seed=42)
tf.random.shuffle(tensor2, seed=24)
tf.random.shuffle(tensor3, seed=32)
tf.random.shuffle(tensor4, seed=45)
tf.random.shuffle(tensor5, seed=54)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 0.66733   , -1.1789492 ,  0.981988  ,  2.1274676 ],
       [-1.5631174 ,  1.2649965 , -1.122423  , -0.3348183 ],
       [-1.3077002 ,  0.09411693, -0.8668549 , -1.9196522 ]],
      dtype=float32)>

#### **It looks like if we want our shuffled tensor to be in the same order, we have to use global level random seed as well as the operational level random seed:**

> Rule 4: If  both the global and the operational seed are set: Both seeds are used in conjunction to determine the random seqeunce

In [ ]:
tf.random.set_seed(42) # global level random seed
tf.random.shuffle(not_shuffled, seed=42) # operational level random seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

### Other ways to make tensor

In [ ]:
# Create a tensor of all ones
tf.ones([10, 7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
# Create a tensor of all zeros
tf.zeros(shape=(3, 4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### Turn NumPy arrays in to TensorFlow tensors

The main differece between **NumPy arrays** and **TensorFlow tensors** is that tensors can be run on a **GPU** (much **faster** for numerical computing) whereas NumPy arrays aree primarily designed to operate on a **CPU**, potentially  making them **slower** for large-scale numerical operations and learning tasks.

In [ ]:
# You can also turn NumPy arrays into TensorFlow tensors
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32)
numpy_A
# X = tf.constant(some_matrix) # Capital for matrix ot tensor
# y = tf.constant(vector) # non-capital for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A = tf.constant(numpy_A)
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [ ]:
# let's change the shape of the tensor 'A'
A = tf.constant(numpy_A, shape=(2, 3, 4))
B = tf.constant(numpy_A)
A, B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

In [ ]:
2 * 3 * 4

24

In [ ]:
A1 = tf.constant(numpy_A, shape=(3, 8))
B1 = tf.constant(numpy_A, shape=(8, 3))
A1, B1

(<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
 array([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>,
 <tf.Tensor: shape=(8, 3), dtype=int32, numpy=
 array([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]], dtype=int32)>)

In [ ]:
print("Number of dimensions as above: \n A: {}, \n A1: {}, \n B: {}, \n B1: {}, ".format(A.ndim, A1.ndim, B.ndim, B1.ndim))

Number of dimensions as above: 
 A: 3, 
 A1: 2, 
 B: 1, 
 B1: 2, 


#### **Practise:** NumPy arrays to TensorFlow tensors


In [ ]:

# Let's start with creating NumPy arrays
import numpy as np
numpy_P = np.arange(1, 37, dtype=np.int32)
numpy_P

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36], dtype=int32)

In [ ]:
# NumPy array to TensorFlow tenors
T = tf.constant(numpy_P)
T

<tf.Tensor: shape=(36,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36], dtype=int32)>

In [ ]:
# Creating a shape for tensor
S = tf.constant(numpy_P, shape=(2, 3, 6))
S

<tf.Tensor: shape=(2, 3, 6), dtype=int32, numpy=
array([[[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18]],

       [[19, 20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35, 36]]], dtype=int32)>

In [ ]:
S1 = tf.constant(numpy_P, shape=(6, 2, 3))
S1

<tf.Tensor: shape=(6, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24]],

       [[25, 26, 27],
        [28, 29, 30]],

       [[31, 32, 33],
        [34, 35, 36]]], dtype=int32)>

### Getting information from tensors

When dealing with tenors you probably want to be aware of the following attributes:
* Shape
* Rank
* Axis or Dimension
* Size

In [ ]:
# Create a rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros(shape=(2, 3, 4, 5))
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
print(rank_4_tensor.shape)
print(rank_4_tensor.ndim)
print(tf.size(rank_4_tensor))

(2, 3, 4, 5)
4
tf.Tensor(120, shape=(), dtype=int32)


In [ ]:
rank_4_tensor.shape,  rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
2 * 3 * 4 * 5

120

In [ ]:
# Get various attributes of our tensor
print("Data type of every element:", rank_4_tensor.dtype)
print("The number of dimensions(rank):", rank_4_tensor.ndim)
print("The shaoe of a tensor:", rank_4_tensor.shape)
print("Elements along 0 axis:", rank_4_tensor.shape[0])
print("Elements along the last axis:", rank_4_tensor.shape[-1])
print("Total number of elements in the tensor:", tf.size(rank_4_tensor))
print("Total number of elements in the tensor:", tf.size(rank_4_tensor).numpy())

Data type of every element: <dtype: 'float32'>
The number of dimensions(rank): 4
The shaoe of a tensor: (2, 3, 4, 5)
Elements along 0 axis: 2
Elements along the last axis: 5
Total number of elements in the tensor: tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in the tensor: 120


In [ ]:
print("Elements along 1st last axis:", rank_4_tensor.shape[2])


Elements along 1st last axis: 4


### Indexing tensors
Tensor can be listed just like Python lists

In [ ]:
some_list = [1, 2, 3, 4]
some_list[:2]

[1, 2]

In [ ]:
# Get the first 2 elements of each dimension
rank_4_tensor[:2, :2, :2, :2]


<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
some_list[:1]

[1]

In [ ]:
rank_4_tensor.shape

TensorShape([2, 3, 4, 5])

In [ ]:
# Get the first element from each dimension from each index except for final one
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
# Create a rank 2 tensor (with 2 dimensions)
rank_2_tensor = tf.constant([[10, 7],
                             [3, 4]])
rank_2_tensor.shape, rank_2_tensor.ndim


(TensorShape([2, 2]), 2)

In [ ]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
some_list, some_list[-1]

([1, 2, 3, 4], 4)

In [ ]:
# Getting the last element of the each row or Getting the last item of rank-2 tensor
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [ ]:
# This acesses the last row of the tensor
rank_2_tensor[-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 4], dtype=int32)>

In [ ]:
# Geting the first row of the tensor
print(rank_2_tensor[1])


tf.Tensor([3 4], shape=(2,), dtype=int32)


In [ ]:
# First element of the each row
print(rank_2_tensor[:, :1])

tf.Tensor(
[[10]
 [ 3]], shape=(2, 1), dtype=int32)


### defination of **...**
**"..."** means every access before the last one and add new acees at the end
e.g: `rank_3_tensor = rank_2_tensor[..., tf.newaxis]` this also same as `rank_3_tensor = rank_2_tensor[:, :, tf.newaxis]`

In [ ]:
# Add in extra dimension to the rank-2 tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [ ]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis = -1) # "-1" means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [ ]:
# xpand the 0-axis
tf.expand_dims(rank_2_tensor, axis = 0) # "-1" means expand the first axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

In [ ]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

### Manipulating tensors(tensor operations)
**Basic Operation**

`+`, `-`, `*`, `/`

In [ ]:
# You can add values to the tensor using the addition operator
tensor = tf.constant([[10, 7], [3, 4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
# Original tensor is unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
# Multiplication also works
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [ ]:
# Subtraction
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

### TensorFlow buil-in function are faster than using basic operation in term of processing time
  it can be used as `tf.math.operation`

In [ ]:
# We can use TensorFlow buil-in function too
print(tf.multiply(tensor, 10))
print(tf.math.multiply(tensor, 5))

tf.Tensor(
[[100  70]
 [ 30  40]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[50 35]
 [15 20]], shape=(2, 2), dtype=int32)


In [ ]:
tf.add(tensor, 8)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[18, 15],
       [11, 12]], dtype=int32)>

In [ ]:
tf.math.subtract(tensor, 3)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[7, 4],
       [0, 1]], dtype=int32)>

In [ ]:
tf.divide(tensor, 3)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[3.33333333, 2.33333333],
       [1.        , 1.33333333]])>

### Manipulating tensors (tensor operations)

**Basic Operations**

`+`, `-`, `*`,  `/`

In [ ]:
# You can add values to the tensor using addition operator
tensor = tf.constant([[10, 7], [3, 4  ]])

### **Matrix multiplication**
In machin learning matrix multiplication is one of the most common tensorflow operations.

There are two rules our tensors ( or matrices) need do fulfill if we're going to matrix multiply them:
1. The inner dimensions must watch
2. The resulting matrix has the shape of the inner dimensions



In [ ]:
# Matrix multiplication is tensorflow
print(tensor)
tf.matmul(tensor, tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
tensor * tensor # This is wrong as elementwise

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]], dtype=int32)>

In [ ]:
# MAtrix multiplication with Python operator
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
tensor.shape

TensorShape([2, 2])

In [ ]:
# Exercise
shape1 = tf.constant([[1, 2, 5],
                      [7, 2, 1],
                      [3, 3, 3]])
shape2 = tf.constant([[3, 5],
                      [6, 7],
                      [1, 8]])

print("This is how does it look like:  /shape 1 \n{} \n shape 2 \n{}".format(shape1, shape2))

This is how does it look like:  /shape 1 
[[1 2 5]
 [7 2 1]
 [3 3 3]] 
 shape 2 
[[3 5]
 [6 7]
 [1 8]]


In [ ]:
tf.matmul(shape1, shape2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [ ]:
# Create tensor (3, 2)
x = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])
# Create another (3, 2) tensor
y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])
x, y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [ ]:
# Try to multiply tesnor of same shape
x @ y

InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2] [Op:MatMul] name: 

In [ ]:
tf.matmul(x, y)

📖 **Resources**: Info and example of matrix multiplication: https://www.mathsisfun.com/algebra/matrix-multiplying.html

In [ ]:
y


In [ ]:
# Let's change shape of y
tf.reshape(y, shape=(2,3))

In [ ]:
x.shape, tf.reshape(x, shape=(3,2))

In [ ]:
# Try to multix multiply x bu reshaped y
x @ tf.reshape(y, shape=(2, 3))

In [ ]:
tf.matmul(x, (tf.reshape(y, shape=(2, 3))))

In [ ]:
tf.reshape(x, shape=(2, 3)).shape, y.shape

In [ ]:
# Try change the shape of x instead of y
tf.matmul(tf.reshape(x, shape=(2,3)), y)

In [ ]:
# Can do the same with tranpose
x, tf.transpose(x), tf.reshape(x, shape=(2, 3))

In [ ]:
x, tf.transpose(x)

In [ ]:
# Try matrix multiplication  with transpose rather than  reshape
tf.matmul(tf.transpose(x), y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

**The dot product**

Matrix multiplication is also referred to as the dot product.

You can perform the matrix multiplication using:
* `tf.matmul()`
* `tf.tensordot()`

In [ ]:
x, y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [ ]:
# Perform the dot product on x and y(requires x or y to be transpose)
tf.tensordot(tf.transpose(x), y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [ ]:
# Perform matrix multiplication between x and y(transposed)
tf.matmul(x, tf.transpose(y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [ ]:
# Perform the matrix multiplication betwen x and y (reshaped)
tf.matmul(x, tf.reshape(y, shape=(2, 3)))


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
# Check the values of y, reshape y and transpose y
print("Normal y: \n {} \n".format(y))
print("y reshaped to (2, 3)")
print(tf.reshape(y, shape=(2, 3)), "\n")
print("y transposed:\n {}".format(tf.transpose(y)))

Normal y: 
 [[ 7  8]
 [ 9 10]
 [11 12]] 

y reshaped to (2, 3)
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

y transposed:
 [[ 7  9 11]
 [ 8 10 12]]


Generally, when performing matrix multiplication, on two tensors and one the axes does not line up, you will transpose one of the tensors (rather than reshaping) to get satisfy matrix multiplication rule.

### Changing  the data type of a tensor


In [ ]:
tf.__version__

'2.15.0'

In [ ]:
# Create a new tensor with default datatype(float32)
B = tf.constant([1.7, 7.4])
B, B.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 7.4], dtype=float32)>,
 tf.float32)

In [ ]:
C = tf.constant([7, 10])
C, C.dtype


(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>,
 tf.int32)

In [ ]:
# Change from float32 to float16(reduced precision)
D = tf.cast(B, dtype=tf.float16)
D, D.dtype


(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>,
 tf.float16)

In [ ]:
# Change from int32 to float32
E = tf.cast(C, dtype=tf.float32)
print(E)

tf.Tensor([ 7. 10.], shape=(2,), dtype=float32)


In [ ]:
E_float = tf.cast(E, dtype=tf.float16)
E_float

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([ 7., 10.], dtype=float16)>

### Aggregating tesnors
 Aggregating tensors = condensing them from multiple values down  to smaller amount of values

In [ ]:
# Get the absolute values
D = tf.constant([-7, 10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([-7, 10], dtype=int32)>

In [ ]:
# Get the absolute values
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

Let's go through the following forms of aggregation:
* Get the minimum
* Get the maximum
* Get the mean of a tensor
* Get the sum of a tensor


In [ ]:
g = tf.constant([[10, 7],
                 [3, 4]])
g

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
# Getting the minimim of the tensror
tf.reduce_min(g)


<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [ ]:
# Getting the maximim of the tensor
tf.reduce_max(g)

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [ ]:
# Gettng the mean of a tesnor
tf.reduce_mean(g)

<tf.Tensor: shape=(), dtype=int32, numpy=6>

In [ ]:
(10+7+3+4)/4

6.0

In [ ]:
# Getting the sum of a tensor
tf.reduce_sum(g)

<tf.Tensor: shape=(), dtype=int32, numpy=24>

In [ ]:
# Create a randm tensor with values between  0 and 100 of size 50
E = tf.constant(np.random.randint(0, 100, size=50))
E


<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([49, 35, 44,  6, 47, 49, 20, 38, 64, 92,  9,  9, 32,  8, 59, 54, 66,
       75, 13, 41, 88, 37, 54, 47, 79, 56, 91, 22,  4, 44, 50,  7, 69, 27,
        2, 41, 64, 98,  7,  8, 77, 44, 57, 39, 90, 57, 87, 54,  9, 83])>

In [ ]:
tf.size(E), E.shape, E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [ ]:
 # Find the minum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2>

In [ ]:
np.min(E)

2

In [ ]:
# Find the maximum
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=98>

In [ ]:
# Find the mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=46>

In [ ]:
# Find the sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2302>

🛠️ **Exercise** With what we've just learned , find the variance and standard deviation of E tensor using TensorFlow methods

In [ ]:

# We need to  cast the matrix — change the datatype from integer to real or complex numbers
E = tf.cast(E, dtype=tf.float32)

In [ ]:
# Vaariance of the matrix
tf.math.reduce_variance(E)

<tf.Tensor: shape=(), dtype=float32, numpy=748.27844>

In [ ]:
# Standard deviation of the matrix
tf.math.reduce_std(E)

<tf.Tensor: shape=(), dtype=float32, numpy=27.354677>

In [ ]:
# To find the variance  of the tensor  using TensorFlow probability
import tensorflow_probability as tfp
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=float32, numpy=748.27844>

###**Find the positional maximum and minimum**

In [ ]:
# Create a new tensor for finding positional minimum and maximum
tf.random.set_seed=42
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
# Find the positional maximum
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
# Index on our  largest value position
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
# Find the max alue of F
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
# CHeck for equality
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [ ]:
# Find the posional minimum
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [ ]:
# Find the minimum using the posinal minimum index
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [ ]:
F[16]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

 **Practising**

In [ ]:
tf.random.set_seed=42
W = tf.random.uniform(shape=[100])
W

<tf.Tensor: shape=(100,), dtype=float32, numpy=
array([0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
       0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256,
       0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ,
       0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ,
       0.13803864, 0.12217975, 0.5754491 , 0.9417181 , 0.9186585 ,
       0.59708476, 0.6109482 , 0.82086265, 0.83269787, 0.8915849 ,
       0.01377225, 0.49807465, 0.57503664, 0.6856195 , 0.75972784,
       0.908944  , 0.40900218, 0.8765154 , 0.53890026, 0.42733097,
       0.401173  , 0.66623247, 0.16348064, 0.18220246, 0.97040176,
       0.06139731, 0.53034747, 0.9869994 , 0.4746945 , 0.8646754 ,
       0.20301068, 0.11448455, 0.35100245, 0.68227184, 0.18108869,
       0.8163481 , 0.65651655, 0.9258256 , 0.2391715 , 0.8365958 ,
       0.04765272, 0.8007157 , 0.8299267 , 0.14328372, 0.8616878 ,
       0.9707202 , 0.6779593 , 0.5641242 , 0.62537   , 0.8653159 ,
       0.16104

In [ ]:
# Find the positional maximun
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
F[12]

<tf.Tensor: shape=(), dtype=float32, numpy=0.13318717>

In [ ]:
# Fnd the maximum value using index
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
# Find the posiotonal minimum
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [ ]:
F[20]

<tf.Tensor: shape=(), dtype=float32, numpy=0.72942245>

In [ ]:
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

### Squeezing a tesnor(removing all single dimensions)

In [ ]:
# Create a tensor to get started
tf.random.set_seed = 42
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1, 1, 1, 1, 50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.7413678 , 0.62854624, 0.01738465, 0.3431449 , 0.51063764,
           0.3777541 , 0.07321596, 0.02137029, 0.2871771 , 0.4710616 ,
           0.6936141 , 0.07321334, 0.93251204, 0.20843053, 0.70105827,
           0.45856392, 0.8596262 , 0.92934334, 0.20291913, 0.76865506,
           0.60016024, 0.27039742, 0.88180614, 0.05365038, 0.42274463,
           0.89037776, 0.7887033 , 0.10165584, 0.19408834, 0.27896714,
           0.39512634, 0.12235212, 0.38412368, 0.9455296 , 0.77594674,
           0.94442344, 0.04296565, 0.4746096 , 0.6548251 , 0.5657116 ,
           0.13858628, 0.3004663 , 0.3311677 , 0.12907016, 0.6435652 ,
           0.45473957, 0.68881893, 0.30203617, 0.49152803, 0.26529062]]]]],
      dtype=float32)>

In [ ]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [ ]:
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.7413678 , 0.62854624, 0.01738465, 0.3431449 , 0.51063764,
        0.3777541 , 0.07321596, 0.02137029, 0.2871771 , 0.4710616 ,
        0.6936141 , 0.07321334, 0.93251204, 0.20843053, 0.70105827,
        0.45856392, 0.8596262 , 0.92934334, 0.20291913, 0.76865506,
        0.60016024, 0.27039742, 0.88180614, 0.05365038, 0.42274463,
        0.89037776, 0.7887033 , 0.10165584, 0.19408834, 0.27896714,
        0.39512634, 0.12235212, 0.38412368, 0.9455296 , 0.77594674,
        0.94442344, 0.04296565, 0.4746096 , 0.6548251 , 0.5657116 ,
        0.13858628, 0.3004663 , 0.3311677 , 0.12907016, 0.6435652 ,
        0.45473957, 0.68881893, 0.30203617, 0.49152803, 0.26529062],
       dtype=float32)>,
 TensorShape([50]))

### One-hot encoding tensors

In [ ]:
# Create a lsit of indices
some_list1 = [0, 1, 2, 3] # could be red, green, blue, purple

# One hot encode our list of indices
tf.one_hot(some_list1, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
# Specify custom values for one hot encoding
tf.one_hot(some_list1, depth=4, on_value=" yo I love deep learning", off_value ="I alsko like to dance")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b' yo I love deep learning', b'I alsko like to dance',
        b'I alsko like to dance', b'I alsko like to dance'],
       [b'I alsko like to dance', b' yo I love deep learning',
        b'I alsko like to dance', b'I alsko like to dance'],
       [b'I alsko like to dance', b'I alsko like to dance',
        b' yo I love deep learning', b'I alsko like to dance'],
       [b'I alsko like to dance', b'I alsko like to dance',
        b'I alsko like to dance', b' yo I love deep learning']],
      dtype=object)>

In [ ]:
# Creata  other  values for one hot encoding
a_list = [1, 2, 3, 4, 5, 6]
tf.one_hot(a_list, depth=8, on_value="Camera Wowo", off_value="Suiiii")

<tf.Tensor: shape=(6, 8), dtype=string, numpy=
array([[b'Suiiii', b'Camera Wowo', b'Suiiii', b'Suiiii', b'Suiiii',
        b'Suiiii', b'Suiiii', b'Suiiii'],
       [b'Suiiii', b'Suiiii', b'Camera Wowo', b'Suiiii', b'Suiiii',
        b'Suiiii', b'Suiiii', b'Suiiii'],
       [b'Suiiii', b'Suiiii', b'Suiiii', b'Camera Wowo', b'Suiiii',
        b'Suiiii', b'Suiiii', b'Suiiii'],
       [b'Suiiii', b'Suiiii', b'Suiiii', b'Suiiii', b'Camera Wowo',
        b'Suiiii', b'Suiiii', b'Suiiii'],
       [b'Suiiii', b'Suiiii', b'Suiiii', b'Suiiii', b'Suiiii',
        b'Camera Wowo', b'Suiiii', b'Suiiii'],
       [b'Suiiii', b'Suiiii', b'Suiiii', b'Suiiii', b'Suiiii', b'Suiiii',
        b'Camera Wowo', b'Suiiii']], dtype=object)>

# Squaring, log, square root

In [ ]:
# Create a new tensor
H = tf.range(1, 10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
# Square it
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
# Find the square root ( will eroor, method requires non-int type)
tf.math.sqrt(H)

InvalidArgumentError: Value for attr 'T' of int32 is not in the list of allowed values: bfloat16, half, float, double, complex64, complex128
	; NodeDef: {{node Sqrt}}; Op<name=Sqrt; signature=x:T -> y:T; attr=T:type,allowed=[DT_BFLOAT16, DT_HALF, DT_FLOAT, DT_DOUBLE, DT_COMPLEX64, DT_COMPLEX128]> [Op:Sqrt] name: 

In [ ]:
# Find the square root
tf.math.sqrt(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.2360678, 2.4494896,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [ ]:
# Find the log
tf.math.log(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Tensors and Numpy
TensorFlow interacts beautifully with TensorFlow

**🔑Note:** One of the main difference between a TensorFlow tensor and a NumPy array is that a TensorFlow can be run on a GPU or TPU(for faster numerical processing).

In [ ]:
# Create a tensor directly from a NumPy array
J = tf.constant(np.array([3., 7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [ ]:
# Convert our tensor back to a NumPy array
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
# Convert tensor J to a NumPy array
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
J = tf.constant([3.])
J.numpy()[0]

3.0

In [ ]:
# The default types of each are slighly different
numpy_J = tf.constant(np.array([3., 7., 10., ]))
tensor_J = tf.constant([3., 7., 10.])
# Check the data types of each are sligtly different
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

### Finding accesss to GPUs

In [ ]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

**🔑Note:** GPU and TPU much faster than CPU

In [ ]:
tf.config.list_physical_devices("GPU")

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
!nvidia-smi

Fri Jul  5 15:15:04 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   65C    P0              31W /  70W |    107MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

**🔑Note:**  If you have access to a CUDA-enabled GPU, TensorFlow will automaticly use it whenever possible