## 🛠 00. TensorFlow Fundamentals Exercises

1. Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().
2. Find the shape, rank and size of the tensors you created in 1.
3. Create two tensors containing random values between 0 and 1 with shape [5, 300].
4. Multiply the two tensors you created in 3 using matrix multiplication.
5. Multiply the two tensors you created in 3 using dot product.
6. Create a tensor with random values between 0 and 1 with shape [224, 224, 3].
7. Find the min and max values of the tensor you created in 6 along the first axis.
8. Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].
9. Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.
10. One-hot encode the tensor you created in 9.


### 1. Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().


In [4]:
import tensorflow as tf

scalar = tf.constant(10)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [6]:
vector = tf.constant([7, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [7]:
matrix = tf.constant([[10, 7], 
                      [7, 10]])

matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

### 2. Find the shape, rank and size of the tensors you created in 1.


In [23]:
print(f"Shape of the scalar is: {scalar.shape}\n Rank of the scalar is: {tf.rank(scalar)}\n The size of the scalar is: {tf.size(scalar)}")

Shape of the scalar is: ()
 Rank of the scalar is: 0
 The size of the scalar is: 1


In [18]:
vector.shape, tf.rank(vector), tf.size(vector)

(TensorShape([2]),
 <tf.Tensor: shape=(), dtype=int32, numpy=1>,
 <tf.Tensor: shape=(), dtype=int32, numpy=2>)

In [22]:
matrix.shape, tf.rank(matrix), tf.size(matrix)

(TensorShape([2, 2]),
 <tf.Tensor: shape=(), dtype=int32, numpy=2>,
 <tf.Tensor: shape=(), dtype=int32, numpy=4>)

### 3. Create two tensors containing random values between 0 and 1 with shape [5, 300].


In [33]:
t1 = tf.random.uniform(shape=(5, 300))
t2 = tf.random.uniform(shape=(5,300))


In [34]:
t1

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.41372168, 0.13940275, 0.47121024, ..., 0.5169922 , 0.58996964,
        0.69652116],
       [0.199157  , 0.4797032 , 0.32584202, ..., 0.97023666, 0.04373002,
        0.2359935 ],
       [0.33479178, 0.9842671 , 0.6115732 , ..., 0.36271715, 0.79367983,
        0.46922278],
       [0.09351969, 0.585166  , 0.8173506 , ..., 0.96331906, 0.5548078 ,
        0.96036375],
       [0.31486213, 0.6901394 , 0.43704414, ..., 0.01954782, 0.57099044,
        0.32338464]], dtype=float32)>

In [35]:
t2

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.21942413, 0.65716743, 0.10962427, ..., 0.51929593, 0.5752076 ,
        0.27780676],
       [0.26421547, 0.3984028 , 0.9900665 , ..., 0.63853836, 0.7151531 ,
        0.57206786],
       [0.13969874, 0.11634898, 0.40005362, ..., 0.5493792 , 0.00673795,
        0.24944448],
       [0.8279816 , 0.48965192, 0.03931963, ..., 0.6146728 , 0.7853261 ,
        0.52869344],
       [0.50245917, 0.06494725, 0.49168563, ..., 0.11369109, 0.20227373,
        0.8608401 ]], dtype=float32)>

4. Multiply the two tensors you created in 3 using **matrix multiplication**.


In [39]:
tf.multiply(t1, t2)

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.09078052, 0.09161095, 0.05165608, ..., 0.26847196, 0.33935502,
        0.19349828],
       [0.05262036, 0.1911151 , 0.32260528, ..., 0.6195333 , 0.03127366,
        0.1350043 ],
       [0.04676999, 0.11451848, 0.24466208, ..., 0.19926926, 0.00534777,
        0.11704504],
       [0.07743258, 0.28652763, 0.03213793, ..., 0.592126  , 0.43570504,
        0.507738  ],
       [0.15820536, 0.04482266, 0.21488832, ..., 0.00222241, 0.11549637,
        0.27838245]], dtype=float32)>

5. Multiply the two tensors you created in 3 using **dot product**

In [44]:
tf.tensordot(t1, t2, axes=0)

<tf.Tensor: shape=(5, 300, 5, 300), dtype=float32, numpy=
array([[[[9.07805189e-02, 2.71884412e-01, 4.53539342e-02, ...,
          2.14843988e-01, 2.37975851e-01, 1.14934683e-01],
         [1.09311670e-01, 1.64827883e-01, 4.09612000e-01, ...,
          2.64177173e-01, 2.95874327e-01, 2.36676872e-01],
         [5.77964000e-02, 4.81360964e-02, 1.65510863e-01, ...,
          2.27290094e-01, 2.78763496e-03, 1.03200592e-01],
         [3.42553943e-01, 2.02579618e-01, 1.62673853e-02, ...,
          2.54303455e-01, 3.24906439e-01, 2.18731940e-01],
         [2.07878247e-01, 2.68700849e-02, 2.03421012e-01, ...,
          4.70364690e-02, 8.36850256e-02, 3.56148213e-01]],

        [[3.05883270e-02, 9.16109458e-02, 1.52819240e-02, ...,
          7.23912790e-02, 8.01855177e-02, 3.87270264e-02],
         [3.68323624e-02, 5.55384457e-02, 1.38017997e-01, ...,
          8.90140012e-02, 9.96943042e-02, 7.97478333e-02],
         [1.94743890e-02, 1.62193682e-02, 5.57685755e-02, ...,
          7.65849724e-0

6. Create a tensor with random values between 0 and 1 with shape [224, 224, 3].


In [48]:
t6 = tf.random.uniform((224, 224, 3))
t6

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.87136793, 0.26574898, 0.831205  ],
        [0.47414482, 0.8858981 , 0.43054533],
        [0.28879154, 0.13658941, 0.8110632 ],
        ...,
        [0.48366666, 0.01154828, 0.02353251],
        [0.55584383, 0.7645427 , 0.5100359 ],
        [0.89572906, 0.7841761 , 0.48912132]],

       [[0.47621977, 0.27888882, 0.6731117 ],
        [0.29805326, 0.11244261, 0.4084195 ],
        [0.387043  , 0.19198179, 0.03853631],
        ...,
        [0.7152611 , 0.1566813 , 0.69803905],
        [0.73154116, 0.48676217, 0.67118406],
        [0.10254943, 0.7945044 , 0.41777003]],

       [[0.13970542, 0.21046174, 0.07429647],
        [0.385247  , 0.7772639 , 0.37330782],
        [0.6534265 , 0.527848  , 0.13293087],
        ...,
        [0.47844493, 0.55113983, 0.73503375],
        [0.45074344, 0.90776706, 0.51820004],
        [0.8138473 , 0.48114288, 0.46437466]],

       ...,

       [[0.5279503 , 0.37634003, 0.13470352],
        [0.44

7. Find the **min** and **max** values of the tensor you created in 6.


In [53]:
print(f"Minimum value of the tensor: {tf.reduce_min(t6)}")
print(f"Max value of the tensor: {tf.reduce_max(t6)}")

Minimum value of the tensor: 3.2186508178710938e-06
Max value of the tensor: 0.9999822378158569


8. Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].


In [54]:
t8 = tf.random.uniform(shape=(1, 224, 224, 3))
t8.shape

TensorShape([1, 224, 224, 3])

In [59]:
t8_squeezed = tf.squeeze(t8)
t8_squeezed.shape

TensorShape([224, 224, 3])

9. Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.


In [89]:
t9 = tf.constant([1, 2, 3, 4, 0.5, 6, 7, 8, 9, 0])
t9

<tf.Tensor: shape=(10,), dtype=float32, numpy=array([1. , 2. , 3. , 4. , 0.5, 6. , 7. , 8. , 9. , 0. ], dtype=float32)>

In [90]:
print(f"Index having max value: {tf.argmax(t9)}\nIndex having min value: {tf.argmin(t9)}")

Index having max value: 8
Index having min value: 9


10. One-hot encode the tensor you created in 9.


In [100]:
t9_cast = tf.cast(t9, dtype=tf.int32)
print(f"Original tensor: {t9}\nCasted tensor: {t9_cast}")

Original tensor: [1.  2.  3.  4.  0.5 6.  7.  8.  9.  0. ]
Casted tensor: [1 2 3 4 0 6 7 8 9 0]


In [103]:
tf.one_hot(t9_cast, depth=len(t9_cast))

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>